### ISSUE TITLE
odd bullets showing up

### ISSUE THREAD

**Issue by LoriStarnes** [michaelbmorris/MichaelBrandonMorris.KingsportMillSafetyTraining#24]
Formatting slides is really difficult.
The view I see on creating a slide is not what shows up in the preview.
There is no way to single space text or to use tab to indent a line.
Using the bullets is really odd - many times additional bullets are showing up between rows instead of on the line of text

![image](https://user-images.githubusercontent.com/31249115/29675675-de850606-88c3-11e7-8b28-5f79e5b75734.png)

**Comment by michaelbmorris** [comment]
New paragraphs have space between them by default. Would you like this space removed? The tab key is not supported due to browser behavior. It causes the browser to move the cursor to the next form field. Indention must be done using the increase/decrease indent buttons. Issues with bullets are likely caused by copy/pasting multiple bullet items from PowerPoint/Word/etc. Try to paste the content as plain text, and then do formatting in the editor.
